main: org.devdhsclub.AmongUsGame.AmongUs
name: AmongUsGame
version: 1.0.0
api-version: 1.16
author: Liam & Ibrahim

commands:
  amongus:
    description: A command used to create an Among Us game in Minecraft.
    usage: /amongus
    aliases:
      - au
